// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Cafeteria_240284.Data;

#nullable disable

namespace Proyecto_Cafeteria_240284.Migrations
{
    [DbContext(typeof(CafeteriaContext))]
    [Migration("20251207023244_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Cafeteria_240284.Models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Café espresso diluido con agua caliente",
                            ImagenUrl = "/images/CafeAmericano.jpg",
                            Nombre = "Café Americano",
                            Precio = 35.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Espresso con leche vaporizada y espuma",
                            ImagenUrl = "/images/cappuccinoAmericano.jpg",
                            Nombre = "Cappuccino",
                            Precio = 45.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Café espresso con abundante leche",
                            ImagenUrl = "/images/Latte.jpg",
                            Nombre = "Latte",
                            Precio = 48.00m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Mezcla de café, chocolate y leche",
                            ImagenUrl = "/images/Moka.jpg",
                            Nombre = "Moka",
                            Precio = 52.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Té de hierbas verdes con hielos",
                            ImagenUrl = "/images/Matcha.jpg",
                            Nombre = "Matcha",
                            Precio = 120m,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("Proyecto_Cafeteria_240284.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "Aaronh",
                            Password = "huerta12.Ar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
